name: build-and-test
on: ["push", "pull_request"]
jobs:
  build-and-test:
    strategy:
      matrix:
        os: [macos-12, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - run: go test ./...
